# Generated by Django 4.1 on 2023-03-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Followers',
        ),
    ]
