# Generated by Django 4.1 on 2023-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
