# Generated by Django 4.1 on 2023-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_perfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
