# Generated by Django 4.1 on 2023-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_perfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfile',
            name='biography',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
