# Generated by Django 4.1 on 2023-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_perfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfile',
            name='ProfileBanner',
            field=models.ImageField(default='bannerDefault.png', upload_to=''),
        ),
    ]
