# Generated by Django 4.1 on 2023-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_perfile_profilebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfile',
            name='ProfileBanner',
            field=models.ImageField(default='bannerDefault.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
