# Generated by Django 4.1 on 2023-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpost',
            old_name='content',
            new_name='postContent',
        ),
    ]
